### PR TITLE
Revert adding serializer

### PR DESCRIPTION
**Pull request by hewison-chris**
The serializer was added to the crypto submodule to facilitate  cross platform hashing. This didn't really work out well due to difficulties when hashing arrays of records with custom hashing.  
The plan was to hash records after they were serialized so that the record length was also hashed as it is already included when serializing. This is fine until you have a struct which has an array of a struct with a custom computeHash. Here if we use the serializer the computeHash is not used. We can handle it in the HashPart function but then we need to hash the array size. So we are back to where we started.

### CODE REVIEW

**Review by kchulj — APPROVED** [review]

**Comment by AndrejMitrovic** [comment]
> This didn't really work out well due to difficulties when hashing arrays of records with custom hashing.

Is there a description of the problem somewhere? I'm out of the loop on this one.

**Comment by hewison-chris** [comment]
> > This didn't really work out well due to difficulties when hashing arrays of records with custom hashing.
> 
> Is there a description of the problem somewhere? I'm out of the loop on this one.

https://github.com/bpfkorea/agora/issues/1331 here is the linked issue with more details.

**Comment by AndrejMitrovic** [comment]
That issue doesn't say anything new though..

**Comment by hewison-chris** [comment]
> That issue doesn't say anything new though..

The reason to not use the serializer?

**Comment by AndrejMitrovic** [comment]
Yeah the last comment is from 20 days ago. Then the serializer was planned to be used, but now it's being reverted?

**Comment by hewison-chris** [comment]
The plan was to hash records after they were serialized so that the record length was also hashed as it is already included when serializing. This is fine until you have a struct which has an array of a struct with a custom computeHash. Here if we use the serializer the computeHash is not used. We can handle it in the HashPart function but then we need to hash the array size. So we are back to where we started.

**Comment by AndrejMitrovic** [comment]
That explains it well. Thank you.

**Comment by hewison-chris** [comment]
> That explains it well. Thank you.

I should have put that in the description to start with.

**Pull request merged**
