### PR TITLE
Merge hashPart routines together 

### PR DESCRIPTION
**Pull request by Geod24**
@hewison-chris : I was trying out a different approach for #4 .
The first step would have been to make the code match more closely what the serializer does, which this does.
It also allowed me to uncover the issue mentioned [here](https://github.com/bpfkorea/crypto/pull/4#issuecomment-779746071). Will write a test for it.

### CODE REVIEW

**Comment by hewison-chris** [comment]
We still need a test for this if we take this approach.

**Comment by Geod24** [comment]
Since it's just merging existing overloads and not adding new stuff, it should be covered by the existing tests, shouldn't it ?

**Review by hewison-chris — APPROVED** [review]
LGTM

**Comment by hewison-chris** [comment]
Can we merge this so I can pull the changes into the other PR?

**Comment by Geod24** [comment]
Sure

**Pull request merged**
