### PR TITLE
Import ECC, Hash, Schnorr, Types from Agora

### PR DESCRIPTION
**Pull request by Geod24**
Those modules can live in their own library and do not need to be in Agora.

I will do a pass over the README (which is clearly incomplete) and the comments in general.

### CODE REVIEW

**Comment by Geod24** [comment]
And we need a CI.

**Comment by Geod24** [comment]
Got the CI to work: https://github.com/Geod24/crypto/actions/runs/546601928
Only need a pass on comments now.

**Comment by AndrejMitrovic** [comment]
Using `agora.` as the top package can become tricky if we ever end up creating a module / package with the same name. E.g. `agora.utils.*` in both Agora and Crypto repos. But I guess we can just be very careful about it.

**Review by AndrejMitrovic — APPROVED** [review]

**Comment by Geod24** [comment]
Indeed. I was trying to think of a good name for this library, because "crypto" is just too generic, but decided to just go the easy way for now.

**Comment by AndrejMitrovic** [comment]
I think we can just go ahead.

**Review by kchulj — APPROVED** [review]

**Pull request merged**
